### ISSUE TITLE
Hide/replace root path string in generated placeholder [[+filelister.path]] link

### ISSUE THREAD

**Issue by wildcat54** [splittingred/FileLister#1]
Hi,
Really good snippet ;)
One feature request: it would be great to be able to hide or replace root path string with a custom one, like 'home'.
Currently [[+filelister.path]] placeholder is returning the root path string ,ie 'assets/.../...', so it shows where the files are located; it would be nice to start with a custom string like 'home' or 'root',

Thanks,
Kevin

**Comment by splittingred** [comment]
Done in 1.0.0-beta2, via the &homePathName property
