### ISSUE TITLE
&showDirectories=`0` doesn't work 

### ISSUE THREAD

**Issue by MrFussyfont** [splittingred/FileLister#10]
It still shows directories. The call I'm using is  
`[[!FileLister? &path=`assets/member/` &allowDownloadGroups=`Members` &requireAuthDownload=`1` showDirectories=`0`]]`

**Comment by splittingred** [comment]
You need an & before the showDirectories property.

**Comment by MrFussyfont** [comment]
Sorry, my bad. It works now.
