### ISSUE TITLE
When not using geolocation the download is never saved to db.

### ISSUE THREAD

**Issue by thojo** [splittingred/FileLister#12]
Shouldn't `$dl->save()` [in line 111](https://github.com/splittingred/FileLister/blob/1.1.0-pl/core/components/filelister/elements/snippets/snippet.filelister.php#L111) be moved out of the if condition `if ($useGeolocation && !empty($geoApiKey)) { ... }` [starting at line 94](https://github.com/splittingred/FileLister/blob/1.1.0-pl/core/components/filelister/elements/snippets/snippet.filelister.php#L94)?

The way it's handled currently, causes that the download is logged only, when using the geolocation feature and I think this is not intended.

**Comment by splittingred** [comment]
Yes, it should. Fixed.
