### ISSUE TITLE
php implode() error

### ISSUE THREAD

**Issue by dsdsdsdsdsds** [splittingred/FileLister#2]
I get the following error with using filelister (has ID 26 on my site):

 [2010-08-15 11:23:03](ERROR @ /home/public_html/core/cache/elements/modsnippet/26.include.cache.php : 248) PHP warning: implode() [<a href='function.implode'>function.implode</a>]: Invalid arguments passed

I checked my setup of filelister but couldn't find any error.

How I call FileLister:
[[!FileLister?
                &path=`assets/media/[[*id]]/`
                &fileTpl=`listIMG`
                &showExt=`jpg,gif,png`
                &showDirectories=`0`
            ]]

listIMG Chunk just outputs an IMG-Element with use of the placeholder [[+path]]

**Comment by splittingred** [comment]
Fixed in 1.0.1

**Comment by dsdsdsdsdsds** [comment]
Hi splittingred,
I first thought the bug doesn't show up anymore but today my site was not available until i deleted the cache. The error log was full of the implode-errors mentioned above. Any idea? If you need more detailed information about the server environment just tell me (what you need).
Thanks!
