### ISSUE TITLE
Geolocation - ipinfodb now requires API key

### ISSUE THREAD

**Issue by odeclas** [splittingred/FileLister#7]
Shaun - all geolocation entries in modx_filelister_downloads are showing : {"Ip":"0.0.0.0","Status":"MOVED","CountryCode":"","CountryName":"","RegionCode":"","RegionName":"","City":"","ZipPostalCode":"","Latitude":"0","Longitude":"0","Timezone":"0","Gmtoffset":"0","Dstoffset":"0"}

Presumably because they've moved server to api.ipinfodb.com, added a $version and need for a key. New class here: http://mirrors.ipinfodb.com/ipinfodb/classes/geolocationapi_class.zip
(not skilled enough to fork and update myself, sorry).

**Comment by odeclas** [comment]
Not sure why this went in closed issues. And now I can't delete and move to Open.

**Comment by splittingred** [comment]
It went in closed because I closed it. ;)

**Comment by odeclas** [comment]
Well. If you're going to be all efficient and fixy, then I'll take my ball and play elsewhere, sir. Chapeau, as ever.

**Comment by splittingred** [comment]
lol. Thanks for reporting the issue. ;)
